apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: crontabs.stable.example.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.example.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              # x-kubernetes-validator:
              #   - rule: "minReplicas <= replicas && replicas <= maxReplicas"
              format: "validation: minReplicas <= replicas && replicas <= maxReplicas"
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
                minReplicas:
                  type: integer
                maxReplicas:
                  type: integer
    - name: v2
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              #format: "conversion:from=v1: {'image2': image}"
              properties:
                cronSpec:
                  type: string
                image2:
                  type: string
                replicas:
                  type: integer
                minReplicas:
                  type: integer
                maxReplicas:
                  type: integer
  conversion:
    #strategy: ConversionRules
    #converters:
    #  - fromVersion: v1
    #    toVersion: v2
    #    rules: # renames the image field from v1 to image2 in v2
    #      field: spec.image2
    #      rule: "spec.image" 
 
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1","v2"]
      clientConfig:
        caBundle: CA_BUNDLE
        url: "https://localhost:8084/validate"
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: crontabs
    # singular name to be used as an alias on the CLI and for display
    singular: crontab
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CronTab
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - ct
