apiVersion: stable.example.com/v1
kind: CronTab
metadata:
  name: "my-crontab"
spec:
  cronSpec: "*/5 * * * *"
  image: "example.gcr.io/cronjobs/myjob:v0.0.1"
  minReplicas: 3
  replicas: 4
  maxReplicas: 5
